version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: stockflow_queue
    ports:
      - "5672:5672"    # Puerto para la comunicación de datos de Node.js (AMQP)
      - "15672:15672"  # Puerto para la interfaz web (Dashboard)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  rabbitmq_data: